pulp-platform/bender

Cargo.lock, Cargo.toml, src/resolver.rs, src/sess.rs
=> Let user resolve dependency conflicts (#2)

.ci/if_deploy_build.sh, .ci/package.sh, .gitignore, .travis.yml
With this patch, Travis build release binaries for Linux and two recent CentOS versions (to precisely match the target libc) for every tag and attaches them as asset to a release on GitHub, see [this example](https://github.com/fabianschuiki/bender/releases/tag/ci-test).
=> Automatically deploy release binaries from Travis

CHANGELOG.md, src/cmd/script.rs
Emit format-specific target defines even if no target is specified.
Previously, `bender script <format>` would emit target-specific (e.g., `'TARGET_SYNTHESIS`) `define`s only if `-t <some target>` was additionally specified.
=> script: Define format-specific targets even if no target is defined

CHANGELOG.md, src/cmd/script.rs
This adds an initial implementation for `bender script vivado`, which outputs commands to add all source files, set all include directories for all files, and set all defines for all files.
This is a very coarse-grained method, but in Vivado the only way to set include directories and defines on a *subset* of files would be to define multiple filesets, which leads to out-of-context synthesis in Vivado, which is not always desirable. We may later add an option to `script vivado` that allows to do this.
I validated the resulting commands in Vivado 2018.3.
=> Add `script vivado`

Cargo.toml
I found this project through crates.io. But there is not link to this repository.
I think the link is useful.
=> Add repository information to Cargo.toml

src/src.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
=> Use `slice::iter` instead of `into_iter` to avoid future breakage

CHANGELOG.md, README.md, src/cmd/script.rs
Adds a `vcs` format to create the compilation script for Synopsys VCS.
Additionally, it adds two options that can only be used with VCS:
- `--vlogan-bin` to specify the binary for analyzing Verilog files
- `--vhdlan-bin` to specify the binary for analyzing VHDL files
TODO:
=> Add support for VCS

CHANGELOG.md, src/cmd/script.rs
Closes #22.
- `script vivado` now emits paths relative to the project root with the `ROOT` variable.
- `script vcs`: Fix shell syntax to define `ROOT` variable.
=> Improve `script`

CHANGELOG.md, src/cmd/script.rs
Closes #23.
- Add `vivado-sim` format to the script command.  This format differs from the `vivado` format in that it targets simulation, not synthesis; other than that, it is equivalent to the `vivado` format.
=> script: Add `vivado-sim` format

CHANGELOG.md, src/cmd/script.rs
This creates a plain file list. No defines, simple includes no file groups. At the moment we need this for the OpenPiton file list in Ariane (https://github.com/pulp-platform/ariane/pull/393).
=> script: Add `flist` target for plain file lists

.travis.yml, CHANGELOG.md, src/cmd/script.rs
This flag causes compilation/analysis scripts to abort on errors that can be caught with Tcl's `catch`.
=> script: Add `--abort-on-error` flag

src/cli.rs
Bender would only check for a Bender.local in the root of the project
but fail to find any other `Bender.local`s on different hierarchy
levels. It now looks for `Bender.local` and `.bender.yml`.
=> cli: Also look for Bender.local recursively

CHANGELOG.md, src/cmd/script.rs
Add a flag (`--defines`) which allows giving additional defines through the command line
=> Add command line argument for defines

.travis.yml, README.md
- Add table of contents to ReadMe.
- Add an *Installation* section, which describes three alternative methods to obtain Bender, to the ReadMe.
- Extend automatic builds to Ubuntu and more versions of CentOS.
For the first installation method to work, GitHub pages on this repository needs to be activated on the `website` branch.
=> Extend Bender availability

src/sess.rs
While attempting to use plugin scripts with bender, I noticed that plugins defined in the main repository's bender file would not be found. I believe this fixes the issue, albeit not very cleanly (first time using rust).
=> Bugfix: plugins work for scripts in the root repository

CHANGELOG.md, README.md, src/cli.rs, src/cmd/clone.rs, src/cmd/mod.rs, src/cmd/parents.rs, src/cmd/workon.rs, src/sess.rs
Added `clone` command to copy a git dependency to a workable location, adding a path override to Bender.local.
Added `parents` command to list packages calling a specified package.
=> Added `clone` and `parents` command for improved workflow

tests/iss2_empty_dep_test.sh, tests/iss5_checkout_branch_test.sh
Recent versions of Git default to `main` as default branch name.  This causes the `iss5` test to fail.  This PR fixes this in a backwards-compatible way.
Additionally, `rev` in the `iss2` test is updated to use `main` as default branch name.
=> Fix tests on recent Git versions

CHANGELOG.md, src/cmd/script.rs
Since VCS generates a shell script, we have to wrap the defines in quotes for this case to allow defines like `32'h80000000`. Otherwise, the `'` breaks the shell script.
=> Wrap defines in quotes for the VCS's shell script

.github/workflows/ci.yml
Update CI tests:
- do not cancel jobs if one fails
- Update minimum Rust version to 1.46.0 (due to `bitflags` dependency)
- Properly name tests
=> CI improve

.github/workflows/release.yaml
Drop support for 16.04 LTS and 20.10, both of which have reached EOL, and add 21.04 and 21.10.
Closes #56.
=> CI: Release for all currently supported Ubuntu versions

CHANGELOG.md, src/cli.rs, src/resolver.rs, src/sess.rs
Currently, if a dependency calls itself (or a different dependency subsequently calling itself, or further chains), this creates a dependency loop and results in an infinite loop within bender. This PR returns an error if cyclical dependencies are detected, with hints where to find the issue.
=> Add error on cyclic dependencies to avoid infinite loop

CHANGELOG.md, src/sess.rs
After updating `Bender.yml` with a new dependency not in `Bender.lock`, an error will be returned suggesting to run `bender update` instead of bender panicking without indication what the problem is.
=> Add error handling on dependency mismatch (#60)

CHANGELOG.md, src/git.rs
- Add hint for workaround in issue (#52)
- Change method to get git commit hash from tag (use `git show-ref --dereference` instead of `git rev-parse
--verify HASH^{commit}`). Reduces number of concurrent commands to improve situation for (#52).
=> Improve git handling for issue (#52)

CHANGELOG.md, src/sess.rs
A naming mismatch can currently cause issues, e.g. when using the parents command to identify packages. May be changed to an error in the future to enforce correct behavior.
=> Add warning for name mismatch of dependency and package

CHANGELOG.md, README.md, src/cli.rs, src/cmd/clone.rs, src/sess.rs
- `bender update --fetch` forces a re-fetch of the git dependencies
- `bender --local` disables fetching of remote repositories to avoid internet access
=> Add arguments to manage git fetching

CHANGELOG.md, src/sess.rs
If a git dependency itself contains path dependencies, these should be linked relative to the git dependency, not anything else.
=> Add correct base path to path dependencies in git

CHANGELOG.md, src/cmd/clone.rs, src/cmd/parents.rs, src/cmd/path.rs, src/cmd/script.rs, src/cmd/sources.rs, src/config.rs
Interpret all dependency names as lowercase to allow for custom capitalization, but no difference of the package (i.e. `fpnew` == `FPnew` or `axi` == `AXI`). May also increase compatibility for non-case-sensitive file systems.
=> Dependency names are lowercase to reduce ambiguity

CHANGELOG.md, src/cmd/parents.rs
In case a dependency doesn't have a manifest, the parents command panicks as it cannot read the dependencies from the manifest. This fixes the issue, simply ignoring these dependencies.
=> Fix panic when calling parents

index.html, init
This PR fixes the following error message on `ubuntu 20.04`:
```
curl --proto '=https' https://pulp-platform.github.io/bender/init -sSf | /bin/bash
main: line 276: [: : integer expression expected
```
that arises when calling the install script:  `curl --proto '=https' https://pulp-platform.github.io/bender/init -sSf | /bin/sh`
Furthermore, I adjusted the url to link to the pulp-platform repo instead of Fabian Schuiki personal repo
=> Fix install script error: main: line 276: [: : integer expression expected

CHANGELOG.md, src/cmd/parents.rs, src/resolver.rs
This PR properly links dependencies in a checkout_dir if present, emulating override path dependencies. This allows for a consistent dependency tree after `bender update` is run, as the local manifests are used to assign dependencies for each package, instead of a possibly out of date upstream version.
=> Properly source dependency manifests

src/sess.rs
Add various warnings to provide hints for why a git dependency may be failing. Usually this error will relate to a bad git url, bad access permissions, or a missing ssh key on the git server. Other reasons are possible, but this should provide some hints to a new user.
=> Git permissions

CHANGELOG.md, src/resolver.rs
When releasing a new version of a dependency and updating the reference in a `Bender.yml` file, bender will not immediately find the correct reference when calling `bender update`, although it does fetch the dependency. Calling `bender update` again will fix this, but it should be done in the first step, without causing an error.
This improvement was introduced in v0.22.0 with b42ed72b9dac7b27b1da62c8649b09f558c7982f, but the implementation is incomplete. This change should properly update the dependency list.
=> Fix incomplete dependency version update when refetching from remote

CHANGELOG.md, src/resolver.rs
When running `bender update`, the command may currently panic if the `checkout_dir` directory optionally specified in the top-level `Bender.yml` file does not yet exist
=> Fix panic with checkout_dir if dir does not exist

CHANGELOG.md, src/cli.rs, src/cmd/checkout.rs, src/cmd/mod.rs, src/error.rs
Add `checkout` command to fetch and checkout dependencies. This is automatically taken care of by any script generation/sources command, however some users prefer an explicit command.
=> Add checkout command

CHANGELOG.md, src/cmd/clone.rs, src/config.rs
This removes the requirement to run `bender update` after cloning a dependency. Fixes #46.
=> Update `Bender.lock` when running `bender clone`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/cmd/script.rs
The formality script is slightly so different to the `dc_shell` syntax. This also removes the `define` option which has no meaning for VHDL files (and becomes an error in `formality`).
=> Add formality support

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/cli.rs, src/cmd/checkout.rs, src/cmd/clone.rs, src/cmd/parents.rs, src/cmd/path.rs, src/cmd/script.rs, src/cmd/sources.rs, src/error.rs, src/git.rs, src/main.rs, src/resolver.rs, src/sess.rs
To update further dependencies, the codebase was slightly modified to comply with `async/await`, updating tokio and futures dependencies. Most of the structures were attempted to be kept, but some were modified away from `.and_then` structures for simpler implementation. Due to time constraints, throttling was not fully implemented yet. My own testing did not uncover any issues, also on larger (PULPissimo) repositories, but improved throttling implementation may be necessary.
=> Update tokio, update futures, rewrite for async/await

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/config.rs, src/main.rs
This PR bumps various dependencies ~, and adds compatibility for the changed [`serde_yaml` exported yaml format](https://github.com/dtolnay/serde-yaml/releases/tag/0.9.0) for enum variants to avoid backwards compatibility issues~ ensuring `serde_yaml` uses the compatible parser.
=> Bump serde_yaml, add compat. for old lockfiles

CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs, src/sess.rs
- Partially checkout path dependencies in git dependencies
- Add warnings if manifest file is not found for a dependency
=> Fix path subdependencies in git dependencies

src/src.rs
Include directories may be needed to properly parse files, so this PR enforces keeping `export_incdirs` for dependencies when excluding dependencies, e.g. with `-n` or `-e` flags.
=> Fix: Keep export_incdirs even when excluding deps

CHANGELOG.md, src/cmd/import.rs
Streamline the initialization of an external dependency. In particular:
- Catch missing target dir
- Create initial patch if none exist
=> import: Streamline init of external dependency

init
This script is not fully POSIX-compliant (see shellcheck complaints). Easiest fix is to just use bash.
=> init: Use bash

README.md, src/cli.rs, src/cmd/import.rs, src/cmd/mod.rs, src/cmd/vendor.rs, src/config.rs, src/git.rs
Refactor and extend the `import` subcommand. The most significant changes:
- Rename the subcommand to `vendor`.
- Use sub-sub commands (`init`, `diff`, `patch`) for main functionality. One sub-sub command has to be provided (otherwise the help message will appear)
- Emit format-patches per default for more control over patch contents and improved trackability and upstreamability. The old behaviour (plain diff) can be achieved using the `--plain` flag.
- Make mappings optional (actually they should be used with caution). If no mappings are provided, the directory structure of the dependency will be kept and copied to `target_dir`.
- Add an optional `include_from_upstream` field to specify patterns that need to match the items of the dependency that are to be copied.
More information on the …
=> import: Restructure and extend functionality

CHANGELOG.md, src/cli.rs
Use relative paths in Lockfile if path dependency is in a subdirectory
=> Lockfile: use relative paths if possible

init
As [rhel9 (and thus also almalinux 9) no longer supports `lsb_release`](https://bugzilla.redhat.com/show_bug.cgi?id=2012924), this is a workaround for these distributions (and others that may not support `lsb_release` in the future), fetching the needed information from `/etc/os-release`.
=> Update script for rhel and missing lsb_release

CHANGELOG.md, src/cli.rs, src/cmd/path.rs
Reduce bender's footprint by skipping checkout of a package if the package path already exists and
- `path` is executed (can be overruled by new `--checkout` flag), or
- for locally linked packages if any command except for `update` is executed.
To prevent `bender path` from returning stale paths, a checkout is now performed automatically after executing `update`. This can be prevented by passing the new `--no-checkout` flag to `update`.
=> path: Skip checkout if possible

src/sess.rs
After a (bad) force push on a branch of an IP commits might disappear. Bender is then not able to run a proper `bender checkout` anymore. The standard error message is not helpful explaining what happened.
=> Improve error message when commit on remote disappears

CHANGELOG.md, src/cli.rs, src/cmd/init.rs, src/cmd/mod.rs
=> Bender init command

README.md
As can be observed in the following lines, the filesystem is traversed upwards to search for configuration files. Configuration files which are reached later override previous configuration files.
https://github.com/pulp-platform/bender/blob/25c518464b6a0c098e815c84f055e8fc2a4829f1/src/cli.rs#L369-L374
https://github.com/pulp-platform/bender/blob/25c518464b6a0c098e815c84f055e8fc2a4829f1/src/config.rs#L702-L714
This PR amends the description in `README.md`.
=> README.md: Correct description of configuration merging logic

CHANGELOG.md, src/cmd/script.rs
Ensure defines/includes/sources are included in script when specifying multiple `--only-*`.
=> Fix script when specifying multiple `--only-*`

src/cmd/clone.rs
All other path dependencies are relative if possible in the lockfile, so we align to this behavior introduced in v0.27.0.
=> Add a relative path to the lockfile for bender clone

src/script_fmt/vcs_sh.tera
Change the VCS compile script template to start with a 
```set -e```
to ensure error propagation to fix #163.
=> Add error prop to generated vcs compile script

src/cmd/vendor.rs, src/config.rs
vendor did not handle it well when multiple files/directories were copied together into one (as is done in [croc](https://github.com/pulp-platform/croc/blob/ee968d10696f6081ef8feb82292cda7b2232cdbc/Bender.yml#L173)).
Fixing it involved prioritizing more specific mappings (eg file to file) over less specific ones (dir to dir) and excluding already diffed files when handling their parent directories.
Also fixes an annoying warning caused by a default configuration.
Tested `bender vendor init` and one random patch with `bender vendor patch` in opentitan_peripherals, register_interface, redundancy_cells and croc. The resulting directories were identical to upstream so it is unlikely to break compatibility with existing configurations.  
It should just make it possible to use more elaborate …
=> Fix mapping limitation in vendor

src/cli.rs
=> Add warning about overrides used

src/git.rs, src/sess.rs
When creating a database from a git repository, bender currently fetches all branches and tags from the remote before checking out the specified reference. However, it is possible that a commit does not belong to a branch or a tag. For instance, GitHub creates PR merge commits and stores their references in `refs/pull`. To checkout such a branchless commit, it must first be fetched explicitly.
Therefore, when creating the database, explicitly fetch the specified reference in addition to all branches and tags (those are still needed e.g. for `bender update`).
An open corner case is when `Bender.lock` is updated with a branchless commit hash after creating the database, but the manifest is not. This will skip fetching altogether and the database might not contain the desired branchless …
=> git-checkout: Support branchless commits

src/cmd/vendor.rs
I'm working on a project where one vendored dependency uses symlinks for managing different SystemVerilog module versions. This was making bender's vendor commands to try to overwrite the symlink with the actual dereferenced file.
I assume this is not intended and the previous handling of symlinks was only for the special case where a vendored package has a symlink to another external directory. That's why I added another condition where the target of the symlink is an actual directory.
=> Fix copying vendored files when they are symbolic links

src/script_fmt/synopsys_tcl.tera
The include directories of dependencies defined as path, which are outside of the `ROOT` directory are not rendered correctly in the synopsys script, since all of them are prefixed with `$ROOT`.
This is a small edge case. Usually dependencies are contained in the `ROOT` folder.
=> Fix include paths in synopsys script

src/sess.rs
For me, the `git tag bender-tmp-<commit> <commit> --force` opens a nano process, which then causes the `bender checkout` to just hang wait for git to complete.
Add a message just to make it go on its merry way.
(An alternate solution would probably be to add `--no-sign`, as this is the cause in my specific case).
cc @niwis
=> git: handle the case where `git tag` opens an editor

src/script_fmt/genus_tcl.tera
This is the same change as in [this commit](https://github.com/pulp-platform/bender/commit/abe9d6825cf4119aea55d663e9159b36e3292f17) but for Genus. Local paths still included $ROOT, while the local path is already normalized.
=> tmpl: Fix prefix for genus include paths

CHANGELOG.md, src/cmd/packages.rs, src/cmd/parents.rs, src/src.rs, src/target.rs
- `parents`: Print currently selected version.
- `packages`: Add `--version` flag to print currently used versions.
- `packages`: Add `--targets` flag to print targets used in the corresponding manifest.
- `packages --graph`: Clean up alignment of output.
=> Add more helpful information printed in subcommands

.github/scripts/gen_dockerfile.sh, .github/scripts/package.sh, .github/workflows/release.yaml, CHANGELOG.md
This PR adds support for building multi-arch releases. See https://github.com/Xeratec/bender/releases/tag/v0.28.3-rc1 for an example.
- New `release_arm64` build stage
- Renamed `release` stage to `release_amd64`
- Fixed `ENV` warning in Dockerfile
- During the build, the release files are placed in `target/<architecture>/<platform>` (e.g. `target/arm64/ubuntu22.04`)
- To keep the release names compatible with earlier releases, `amd64` is replaced with `x86_64`
=> Multi-Arch Releases

init
This PR adapts the download script to support ARM64 builds, as described in #211.
Note: I did not test it on Windows, but as this part of the code is untouched, I argue this is unnecessary.
- Added logic to handle `arm64-linux-gnu` platforms
- Fixed some syntax to work with `sh` (previously only worked bith `bash`)
=> ARM64 Download Script Support
